datasets:
  original: <dataset0> # Original parallel corpus

stages:
  - train

train:
  - original 1.0
  - until original inf # General training until marian early stops

modifiers:
- UpperCase: 0.05 # Apply randomly to 5% of sentences
- TitleCase: 0.05
# TODO: enable typos, issue https://github.com/hplt-project/OpusTrainer/issues/40
#- Typos: 0.05

seed: 1111
num_fields: 2
