datasets:
  original: <dataset0> # Original parallel corpus
#  backtranslated: <dataset1> # Back-translated data

stages:
#  - pretrain
  - finetune

#pretrain:
#  - original 0.5
#  - backtranslated 0.5
#  - until original 2 # General training until 2 epochs of original

finetune:
  - original 1.0
  - until original inf # Fine-tuning only on original until the early stopping


modifiers:
- UpperCase: 0.1 # Apply randomly to 5% of sentences
- TitleCase: 0.1
# TODO: enable typos, issue https://github.com/hplt-project/OpusTrainer/issues/40
#- Typos: 0.05

seed: 1111
num_fields: 2
