# Example of a production config for Taskcluster
#
# See the training guide for more information:
#   https://mozilla.github.io/firefox-translations-training/training-guide.html
#
# The defaults for these parameters are available at:
#   taskcluster/translations_taskgraph/parameters.py

# An "experiment" is an individual training run.
experiment:
  # Provide an identifiable name for your experiment.
  name: baseline_en_fi

  # The source and target languages. This is the language tag part of the
  # BCP 47 locale identifier.
  src: en
  trg: fi

  # The metric to use for computing the best model validation.
  #   cross-entropy, ce-mean-words, perplexity, valid-script, translation, bleu,
  #   bleu-segmented, chrf
  # See: https://github.com/marian-nmt/marian/blob/65bf82ffce52f4854295d8b98482534f176d494e/src/common/config_parser.cpp#L588-L592
  best-model: chrf

  # Use the Opus Cleaner tool on the data cleaning step.
  # https://github.com/hplt-project/OpusCleaner
  use-opuscleaner: "true"

  # Bicleaner is a tool that aims at detecting noisy sentence pairs in a parallel corpus.
  # See: docs/bicleaner.md
  bicleaner:
    default-threshold: 0.5
    dataset-thresholds:
      opus_CCAligned/v1: 0.7
      opus_LinguaTools-WikiTitles/v2014: 0.7
      opus_OpenSubtitles/v2018: 0.8           # Example of a higher filtering level.
      opus_WikiMatrix/v1: 0.7
      opus_bible-uedin/v1: 0.7

  # Limits the maximum sentences use in the monolingual data for both the source and target
  # languages.
  mono-max-sentences-src: 100_000_000
  mono-max-sentences-trg: 20_000_000

  # How many bytes of the corpus are sampled to be used in SentencePiece
  # tokenization training.
  spm-sample-size: 10_000_000

  # Determine how many teachers to train.
  # See: docs/teacher-ensemble.md
  teacher-ensemble: 2

  # Path to a pretrained backward model (optional).
  backward-model: NOT-YET-SUPPORTED

  # Path to a pretrained vocabulary (optional).
  vocab: NOT-YET-SUPPORTED
  
  # Continue training see docs/using-pretrained-models.md
  pretrained-models:
    train-backwards:
      urls:
        - https://storage.googleapis.com/releng-translations-dev1/models/en-fi/opusmt/student/
      mode: use
      type: default

# The lists of datasets. Each dataset is defined by a corpus key. This key is formed
# by "{IMPORTER}_{DATASET}". These datasets and their corpus key can be found through
#
# TODO(docs) - Document augmentation in corpus keys.
#
# To find datasets run:
#  poetry run utils/find_corpus.py en ru
datasets:
  # The datasets used for validation while training. These should not be the same
  # ones used in test or train. This is what is used to determine when to stop training.
  devtest:
    - flores_dev
    - sacrebleu_wmt08
    - mtdata_Neulab-tedtalks_dev-1-eng-fin
    - sacrebleu_wmt15
    - sacrebleu_wmt17
    - sacrebleu_wmt19

  # The datasets used for the final evaluation to determine the quality of the trained
  # model.
  test:
    - flores_devtest
    - sacrebleu_wmt16
    - sacrebleu_wmt18
    - mtdata_Neulab-tedtalks_test-1-eng-fin

  # The parallel training data.
  train:
    - opus_Books/v1
    - opus_CCAligned/v1
    - opus_CCMatrix/v1
    - opus_DGT/v2019
    - opus_ECB/v1
    - opus_ECDC/v2016-03-16
    - opus_ELITR-ECA/v1
    - opus_ELRA-W0217/v1
    - opus_ELRA-W0220/v1
    - opus_ELRA-W0305/v1
    - opus_ELRC-1127-www.vtv.fi/v1
    - opus_ELRC-1128-www.visitestonia.com/v1
    - opus_ELRC-1769-valtioneuvosto.fi/v1
    - opus_ELRC-1771-vnk.fi/v1
    - opus_ELRC-2017-EUIPO_2017/v1
    - opus_ELRC-2032-www.turku.fi/v1
    - opus_ELRC-2036-www.vero.fi/v1
    - opus_ELRC-2708-EMEA/v1
    - opus_ELRC-2739-vaccination/v1
    - opus_ELRC-2869-EU_publications_medi/v1
    - opus_ELRC-3045-wikipedia_health/v1
    - opus_ELRC-3196-antibiotic/v1
    - opus_ELRC-3287-EUROPARL_covid/v1
    - opus_ELRC-3458-EC_EUROPA_covid/v1
    - opus_ELRC-3559-EUR_LEX_covid/v1
    - opus_ELRC-3600-presscorner_covid/v1
    - opus_ELRC-401-Swedish_Labour_Part2/v1
    - opus_ELRC-406-Swedish_Labour_Part1/v1
    - opus_ELRC-416-Swedish_Social_Secur/v1
    - opus_ELRC-4239-NTEU_TierA/v1
    - opus_ELRC-436-Swedish_Food/v1
    - opus_ELRC-4995-Finnish_Financial_MT/v1
    - opus_ELRC-5067-SciPar/v1
    - opus_ELRC-716-Finnish_Information_/v1
    - opus_ELRC-724-Hallituskausi_2007_2/v1
    - opus_ELRC-725-Hallituskausi_2011_2/v1
    - opus_ELRC-735-www.norden.org/v1
    - opus_ELRC-EC_EUROPA/v1
    - opus_ELRC-EMEA/v1
    - opus_ELRC-EUIPO_2017/v1
    - opus_ELRC-EUROPARL_covid/v1
    - opus_ELRC-EUR_LEX/v1
    - opus_ELRC-EU_publications/v1
    - opus_ELRC-Finnish_Information/v1
    - opus_ELRC-Swedish_Labour/v1
    - opus_ELRC-antibiotic/v1
    - opus_ELRC-presscorner_covid/v1
    - opus_ELRC-vaccination/v1
    - opus_ELRC-valtioneuvosto.fi/v1
    - opus_ELRC-vnk.fi/v1
    - opus_ELRC-wikipedia_health/v1
    - opus_ELRC-www.norden.org/v1
    - opus_ELRC-www.turku.fi/v1
    - opus_ELRC-www.vero.fi/v1
    - opus_ELRC-www.visitestonia.com/v1
    - opus_ELRC-www.vtv.fi/v1
    - opus_ELRC_2922/v1
    - opus_ELRC_2923/v1
    - opus_ELRC_3382/v1
    - opus_EMEA/v3
    - opus_EUbookshop/v2
    - opus_EUconst/v1
    - opus_Europarl/v8
    - opus_GNOME/v1
    - opus_HPLT/v1.1
    - opus_JRC-Acquis/v3.0
    - opus_KDE4/v2
    - opus_LinguaTools-WikiTitles/v2014
    - opus_MultiHPLT/v1.1
    - opus_NLLB/v1
    - opus_NeuLab-TedTalks/v1
    - opus_OpenSubtitles/v2018
    - opus_PHP/v1
    - opus_ParaCrawl/v9
    - opus_QED/v2.0a
    - opus_TED2020/v1
    - opus_Tatoeba/v2023-04-12
    - opus_TildeMODEL/v2018
    - opus_Ubuntu/v14.10
    - opus_WikiMatrix/v1
    - opus_XLEnt/v1.2
    - opus_bible-uedin/v1
    - opus_infopankki/v1
    - opus_wikimedia/v20230407

  # Monolingual data sources for the source language.
  mono-src:
    - news-crawl_news.2023
    - news-crawl_news.2022
    - news-crawl_news.2021
    - news-crawl_news.2020
    - news-crawl_news.2019
    - news-crawl_news.2018
    - news-crawl_news.2017
    - news-crawl_news.2016
    - news-crawl_news.2015
    - news-crawl_news.2014
    - news-crawl_news.2013
    - news-crawl_news.2012
    - news-crawl_news.2011
    - news-crawl_news.2010
    - news-crawl_news.2009
    - news-crawl_news.2008
    - news-crawl_news.2007

  # Monolingual data sources for the target language.
  mono-trg:
    - news-crawl_news.2023
    - news-crawl_news.2022
    - news-crawl_news.2021
    - news-crawl_news.2020
    - news-crawl_news.2019
    - news-crawl_news.2018
    - news-crawl_news.2017
    - news-crawl_news.2016
    - news-crawl_news.2015
    - news-crawl_news.2014

# Arguments that are provided to Marian, the underlying machine learning system used
# to train language.
# https://marian-nmt.github.io/docs/cmd/marian/
marian-args:
  # Decoding arguments are GPU-dependent. See:
  # https://mozilla.github.io/firefox-translations-training/training-guide.html#decoding-translation
  decoding-backward:
    beam-size: '12'
    mini-batch-words: '2000'
  decoding-teacher:
    mini-batch-words: '4000'
    precision: float16

  # Early stopping can be adjusted to ensure models converge. See:
  # https://mozilla.github.io/firefox-translations-training/training-guide.html#model-training
  training-backward:
    early-stopping: '5'
  training-teacher:
    early-stopping: '30'
  training-student:
    early-stopping: '20'
  training-student-finetuned:
    early-stopping: '20'

# Run all of the training pipeline with "all", or run a specific stage such as
# "merge-corpus". For more information see:
#
# https://mozilla.github.io/firefox-translations-training/task-cluster.html#running-up-to-a-specific-step
target-stage: all

taskcluster:
  # After the parallel corpora are merged and de-duplicated, the combined file is
  # then split into an even number of chunks.
  split-chunks: 10
