####
# Test config, it rus the pipeline quickly end to end
###

experiment:
  name: test
  src: ru
  trg: en

  teacher-ensemble: 2
  backward-model: ""
  vocab: ""

  mono-max-sentences-src: 1000
  mono-max-sentences-trg: 1000
  split-length: 100000
  spm-sample-size: 300

  best-model: chrf

  use-opuscleaner: true
  bicleaner:
    default-threshold: 0.5
    dataset-thresholds:
      opus_ada83/v1: 0
      mtdata_Tilde-airbaltic-1-eng-rus: 0.6

marian-args:
  training-backward:
    disp-freq: 10
    save-freq: 100
    valid-freq: 100
    after: 500u
  training-teacher:
    disp-freq: 10
    save-freq: 100
    valid-freq: 100
    after: 500u
  training-student:
    disp-freq: 10
    save-freq: 100
    valid-freq: 100
    after: 500u
  training-student-finetuned:
    disp-freq: 10
    save-freq: 100
    valid-freq: 100
    after: 500u
  decoding-backward:
    mini-batch-words: 2000
  decoding-teacher:
    mini-batch-words: 1000
    precision: float16

datasets:
  train:
    - opus_ada83/v1                        # 4122 sentences
    - opus_GNOME/v1                        # 150 sentences
    - mtdata_Tilde-airbaltic-1-eng-rus     # 1000 sentences
  devtest:
    - flores_dev
    - sacrebleu_wmt19
  test:
    - flores_devtest
    - sacrebleu_wmt20
  mono-src:
    - news-crawl_news.2020
  mono-trg:
    - news-crawl_news.2020
