# Example of a production config for Taskcluster
#
# See the training guide for more information:
#   https://mozilla.github.io/firefox-translations-training/training-guide.html
#
# The defaults for these parameters are available at:
#   taskcluster/translations_taskgraph/parameters.py

# An "experiment" is an individual training run.
experiment:
  # Provide an identifiable name for your experiment.
  name: en_ca_alldata_no_clean_nllb

  # The source and target languages. This is the language tag part of the
  # BCP 47 locale identifier.
  src: en
  trg: ca

  # The metric to use for computing the best model validation.
  #   cross-entropy, ce-mean-words, perplexity, valid-script, translation, bleu,
  #   bleu-segmented, chrf
  # See: https://github.com/marian-nmt/marian/blob/65bf82ffce52f4854295d8b98482534f176d494e/src/common/config_parser.cpp#L588-L592
  best-model: chrf

  # Disable opus cleaner since this is a baseline run.
  use-opuscleaner: "false"

  # Bicleaner is a tool that aims at detecting noisy sentence pairs in a parallel corpus.
  # See: docs/bicleaner.md
  bicleaner:
    default-threshold: 0.5
    dataset-thresholds:
      opus_NLLB/v1: 0.0              # Do not clean NLLB
      opus_OpenSubtitles/v2018: 0.8  # This is dirty per bicleaner.md

  # Limits the maximum sentences use in the monolingual data for both the source and target
  # languages.
  mono-max-sentences-src: 100_000_000
  # 73,031,398
  mono-max-sentences-trg: 100_000_000

  # The number of sentences split out into separate files for the monolingual data.
  # Also see taskcluster.split-chunks below.
  split-length: 2_000_000

  # How many bytes of the corpus are sampled to be used in SentencePiece
  # tokenization training.
  spm-sample-size: 10_000_000

  # Determine how many teachers to train.
  # See: docs/teacher-ensemble.md
  teacher-ensemble: 1

  # TODO(docs) - What is this?
  backward-model: NOT-YET-SUPPORTED

  # TODO(docs) - What is this?
  vocab: NOT-YET-SUPPORTED

# The lists of datasets. Each dataset is defined by a corpus key. This key is formed
# by "{IMPORTER}_{DATASET}". These datasets and their corpus key can be found through
#
# TODO(docs) - Document augmentation in corpus keys.
#
# running:
#  utils/find_corpus.py
datasets:
  # The datasets used for validation while training. These should not be the same
  # ones used in test or train. This is what is used to determine when to stop training.
  devtest:
    # 997 sentences
    - flores_devtest

  # The datasets used for the final evaluation to determine the quality of the trained
  # model.
  test:
    # 1012 sentences
    - flores_dev

  # The parallel training data.
  train:
    - opus_Books/v1
    - opus_CCAligned/v1
    - opus_ELRC-3040-wikipedia_health/v1
    - opus_ELRC-5129-GEnCaTA_a/v1
    - opus_ELRC-5189-Catalan_WMT2013_Mach/v1
    - opus_ELRC-5190-Cyber_MT_Test/v1
    - opus_ELRC-wikipedia_health/v1
    - opus_ELRC_2922/v1
    - opus_EUbookshop/v2
    - opus_GNOME/v1
    - opus_GlobalVoices/v2018q4
    - opus_HPLT/v1.1
    - opus_KDE4/v2
    - opus_MaCoCu/v2
    - opus_MultiHPLT/v1.1
    - opus_MultiMaCoCu/v2
    - opus_NLLB/v1
    - opus_OpenSubtitles/v2018
    - opus_QED/v2.0a
    - opus_TED2020/v1
    - opus_Tatoeba/v2023-04-12
    - opus_Ubuntu/v14.10
    - opus_WikiMatrix/v1
    - opus_XLEnt/v1.2
    - opus_tldr-pages/v2023-08-29
    - opus_wikimedia/v20230407

  # Monolingual data sources for the source language.
  mono-src:
    - news-crawl_news.2021
    - news-crawl_news.2020
    - news-crawl_news.2019
    - news-crawl_news.2018
    - news-crawl_news.2017
    - news-crawl_news.2016
    - news-crawl_news.2015
    - news-crawl_news.2014
    - news-crawl_news.2013
    - news-crawl_news.2012
    - news-crawl_news.2011
    - news-crawl_news.2010
    - news-crawl_news.2009
    - news-crawl_news.2008
    - news-crawl_news.2007

  # Monolingual data sources for the target language.
  mono-trg:
    - bucket_releng-translations-dev/data/en-ca/catalan_textual_corpus

# Arguments that are provided to Marian, the underlying machine learning system used
# to train language.
# https://marian-nmt.github.io/docs/cmd/marian/
marian-args:
  # Decoding arguments are GPU-dependent. See:
  # https://mozilla.github.io/firefox-translations-training/training-guide.html#decoding-translation
  decoding-backward:
    beam-size: '12'
    mini-batch-words: '2000'
  decoding-teacher:
    mini-batch-words: '4000'
    precision: float16

  # Early stopping can be adjusted to ensure models converge. See:
  # https://mozilla.github.io/firefox-translations-training/training-guide.html#model-training
  training-backward:
    early-stopping: '5'
  training-teacher:
    early-stopping: '30'
  training-student:
    early-stopping: '20'
  training-student-finetuned:
    early-stopping: '20'

# Run all of the training pipeline with "all", or run a specific stage such as
# "merge-corpus". For more information see:
#
# https://mozilla.github.io/firefox-translations-training/task-cluster.html#running-up-to-a-specific-step
target-stage: train-teacher

taskcluster:
  # After the parallel corpora are merged and de-duplicated, the combined file is
  # then split into an even number of chunks.
  split-chunks: 10

# # Continue training see docs/using-pretrained-models.md
# pretrained-models:
#   # Re-use an existing backwards model from a Google Cloud Storage bucket.
#   train-backwards:
#     urls:
#       - https://storage.googleapis.com/bucket-name/models/ru-en/backward
#     mode: use
#     type: default
